- name: create curator.list
  copy: src=files/curator.list dest=/etc/apt/sources.list.d/curator.list
  become: yes
- name: install elasticsearch-curator
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
  with_items:
    - elasticsearch-curator
  become: yes
