- name: Install ELK6
  hosts: testserver
  vars_files:
    - version.yml
    - config.yml
  environment:
    snort_version: "{{ snort_version }}"
    daq_version: "{{ daq_version }}"
  connection: local
  pre_tasks:
    - set_fact: home_dir="{{ ansible_env.HOME }}"
    - name: set timezone
      script: scripts/set_timezone.sh {{ timezone }}
      become: yes
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - build-essential
        - ntp
        - git
        - curl
        - jq
        - wireshark
      become: yes
    - name: mkdir
      file: path={{ item }}  state=directory mode=0755
      with_items:
        - ~/snort/log
        - ~/bin
        - ~/etc
        - ~/.curator
    - name: copy shell scripts
      copy: src=files/{{ item }} dest=~/bin/{{ item }} mode=0755
      with_items:
        - logstash_config_test.sh
    - name: copy curator file
      copy: src=files/{{ item }} dest=~/.curator/{{ item }}
      with_items:
        - curator.yml
        - delete_indices_snort.yml
    - name: set crontab
      script: scripts/cron_curator.sh
  roles:
    - role: snort
    - role: elasticsearch
    - role: logstash
    - role: kibana
    - role: elasticsearch-curator
    - role: grafana
