- name: Install ELK6
  hosts: testserver
  vars_files:
    - version.yml
    - config.yml
  environment:
    snort_version: "{{ snort_version }}"
    daq_version: "{{ daq_version }}"
  connection: local
  pre_tasks:
    - set_fact: home_dir="{{ ansible_env.HOME }}"
    - name: set timezone
      script: scripts/set_timezone.sh {{ timezone }}
      become: yes
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes
      become: yes
      with_items:
        - ntp
        - git
        - curl
        - jq
        - wireshark
        - libpcap-dev
        - libpcre3-dev
        - libdumbnet-dev
        - bison
        - flex
        - mysql-server
        - mysql-client
        - libmysqlclient-dev
        - autoconf
        - libtool
        - zlib1g-dev
        - liblzma-dev
        - openssl
        - libssl-dev
        - libnghttp2-dev
        - libcrypt-ssleay-perl
        - liblwp-useragent-determined-perl
    - name: compile daq
      script: scripts/compile_daq.sh
      become: yes
    - name: compile snort
      script: scripts/compile_snort.sh
      become: yes
    - name: mkdir
      file: path={{ item }}  state=directory mode=0755
      with_items:
        - ~/snort/log
        - ~/bin
        - ~/etc
        - ~/.curator
    - name: copy shell scripts
      copy: src=files/{{ item }} dest=~/bin/{{ item }} mode=0755
      with_items:
        - logstash_config_test.sh
    - name: copy curator file
      copy: src=files/{{ item }} dest=~/.curator/{{ item }}
      with_items:
        - curator.yml
        - delete_indices_snort.yml
    - name: set crontab
      script: scripts/cron_curator.sh
  roles:
    - role: elasticsearch
    - role: logstash
    - role: kibana
    - role: elasticsearch-curator
    - role: grafana
