- name: install openjdk-8-jdk apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - openjdk-8-jdk
  become: yes
- name: install logstash apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - logstash
  become: yes
- name: copy logstash config file
  copy: src=files/logstash_snort.conf dest=/etc/logstash/conf.d/logstash_snort.conf
  become: yes
  notify: restart logstash
